modLoader="javafml"
loaderVersion="[1,)"
license="AGPL-3.0"
issueTrackerURL="https://github.com/xingchentye/MinecraftTerracotta/issues"

[[mods]]
modId="minecraftterracotta"
version="0.1.0"
displayName="MinecraftTerracotta"
authors="xingchentye"
description='''
MinecraftTerracotta Mod
Simple and easy-to-use P2P multiplayer solution for Minecraft.
Powered by Terracotta backend.
'''
logoFile="icon.png"

[[dependencies.minecraftterracotta]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minecraftterracotta]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
