modLoader="javafml"
loaderVersion="[1,)"
license="AGPL-3.0"

[[mods]]
modId="ender_online"
version="0.1.2"
displayName="EnderOnline"
authors="xingchentye"
description='''
Simple and easy-to-use P2P multiplayer solution for Minecraft.
'''

[[dependencies.ender_online]]
modId="neoforge"
type="required"
versionRange="[21.1.218,)"
ordering="NONE"
side="BOTH"

[[dependencies.ender_online]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

